SCAM_GROUPS = {
    1: "Lừa đảo đặt bàn ăn",
    2: "Lừa đảo đặt phòng khách sạn",
    3: "Lừa đảo định danh CCCD",
    4: "Lừa đảo giả cơ quan nhà nước (GTVT, TTTT...)",
    5: "Lừa đảo giả danh cơ quan thuế",
    6: "Lừa đảo giả danh công an",
    7: "Lừa đảo giả mạo thương hiệu, tổ chức (Điện lực, viễn thông...)",
    8: "Lừa đảo giả sàn thương mại điện tử",
    9: "Lừa đảo giao đơn hàng không có thực",
    10: "Lừa đảo hải quan nộp phạt",
    11: "Lừa đảo khóa SIM",
    12: "Lừa đảo máy lọc nước",
    13: "Lừa đảo mở, rút tiền thẻ tín dụng",
    14: "Lừa đảo PCCC",
    15: "Lừa đảo sử dụng trang web giả mạo",
    16: "Lừa đảo ứng dụng ví điện tử / ví trả sau",
    17: "Thông báo nhận tiền hỗ trợ, trợ cấp an sinh xã hội",
    18: "Lừa đảo vay vốn",
    19: "Lừa đảo cài ứng dụng độc hại",
    20: "Lừa đảo lợi dụng sự cố mất an toàn thông tin",
    21: "Lừa đảo báo lỗi tài khoản",
    22: "Lừa đảo từ thiện",
    23: "Lừa đảo mạo danh người thân quen",
    24: "Lừa đảo lấy lại tiền treo, tiền bị lừa",
    25: "Lừa đảo đe dọa sự việc không có thực",
    26: "Lừa đảo trúng tuyển, tuyển sinh",
    27: "Lừa đảo thanh toán tiền giao hàng",
    28: "Lừa đảo đầu tư tiền ảo",
    29: "Lừa đảo mạo danh bác sĩ, cơ sở y tế"
}
